# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = uwsm app -- hyprsunset
exec-once = sleep 3 && pw-loopback --capture alsa_input.pci-0000_0a_00.4.analog-stereo --latency 50
