# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

monitor = HDMI-A-1, 3840x2160@119.88, auto, 1
